apiVersion: v1
kind: Service
metadata:
  name: smartjogger-service
  labels:
    app: smartjogger
spec:
  type: NodePort
  selector:
    app: smartjogger
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
